openapi: 3.0.3
info:
  title: Invoice Collector Container
  version: '0.1'
servers:
  - url: https://localhost:8080/api/v1
paths:
  "/ping":
    post:
      summary: Ping
      description: Ping the _Invoice-Collector Container_ and the _Invoice-Collector Server_.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/pong"
  "/collectors":
    get:
      summary: Collectors
      description: List all the available collectors.
      responses:
        '200':
          description: List of available collectors
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/collector"
  "/collect":
    post:
      summary: Collect invoices
      description: Collect invoices for the given collector.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                collector:
                  type: string
                  description: Key of the collector to use.
                  example: free
                callback:
                  type: string
                  description: Callback URL to send the collected invoices to.
                  format: uri
                  example: https://localhost:1234/my/callback
                params:
                  type: object
                  description: Parameters required by the collector.
                  example:
                    username: fbx123456789
                    passsword: Y%2j7Fc$#$y
                metadata:
                  type: object
                  description: Metadata to send to the callback.
                  example:
                    key: this value will be passed to the callback uri
              required:
              - callback
              - collector
              - params
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                description: Request in process.
                properties:
                  id:
                    type: string
                    description: Request id
                    example: 514
                  collector:
                    type: string
                    description: Key of the collector
                    example: free
                required:
                - id
                - collector
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                description: Error response
      callbacks:
        onInvoiceCollected:
          Callback:
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Request id.
                          example: 514
                        collector:
                          type: string
                          description: Key of the collector.
                          example: free
                        type:
                          type: string
                          description: If the collect request returned invoices or an error.
                          enum:
                            - invoices
                            - error
                          example: invoices
                        invoices:
                          "$ref": "#/components/schemas/invoices"
                        error:
                          "$ref": "#/components/schemas/error"
                        metadata:
                          type: object
                          description: Metadata passed in the collect request.
                          example:
                            key: this value will be passed to the callback uri
                      required:
                        - type
                        - metadata
              responses:
                '200':
                  description: Success
  "/new_collector":
    post:
      summary: New collector
      description: Request a new collector.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  description: Name of the new collector.
                  example: free
                link:
                  type: string
                  description: Link to the website of the new collector.
                  format: uri
                  example: https://www.free.fr
              required:
                - name
                - link
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    pong:
      type: object
      properties:
        client:
          type: string
          description: Client that sent the request, `null` if the client could not be found.
          example: My-Company-Name
        type:
          type: string
          description: Type of the response.
          enum:
          - success
          - warning
          - error
          example: success
        message:
          type: string
          description: Message from the server.
          example: Great job! You can reach the server and you are ready to collect invoices...
      required:
      - client
      - type
      - message
    collector:
      type: object
      properties:
        collector:
          type: string
          description: Key of the collector. This key is used to identify the collector in the collect request.
          example: free
        name:
          type: string
          description: Name of the collector.
          example: Free
        description:
          type: string
          description: Description of the collector.
          example: Free is a French telecommunications company
        version:
          type: string
          description: Version of the collector.
          example: 1
        website:
          type: string
          description: Link to the website of the collector.
          format: uri
          example: https://www.free.fr
        logo:
          type: string
          description: Link to the logo of the collector.
          format: uri
          example: https://fr.wikipedia.org/wiki/Free_(entreprise)#/media/Fichier:Free_logo.svg
        params:
          type: array
          description: List of parameters that the collector requires.
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of the parameter.
                example: username
              description:
                type: string
                description: Description of the parameter.
                example: Email address of the account
              mandatory:
                type: boolean
                description: Whether the parameter is mandatory or not.
                example: true
            required:
            - name
            - description
            - mandatory
      required:
      - collector
      - name
      - description
      - version
      - website
      - logo
      - params
    invoices:
      type: array
      description: List of invoices collected.
      items:
        type: object
        properties:
          id:
            type: string
            description: Unique identifier for the invoice. It changes from collector to collector.
            example: 45FDD1544
          type:
            type: string
            description: Type of the invoice.
            example: base64
          mime:
            type: string
            description: MIME type of the invoice.
            example: application/pdf
          timestamp:
            type: integer
            description: Timestamp when the invoice was created.
            example: 1731603196
          data:
            type: string
            description: Base64 encoded data of the invoice.
            example: iVBORw0KGgoAAAAN...RU5ErkJggg==
        required:
          - id
          - type
          - mime
          - timestamp
          - data
    error:
      type: object
      properties:
        collector:
          type: string
          description: Key of the collector where the error occurred.
          example: free
        version:
          type: string
          description: Version of the collector.
          example: 1
        name:
          type: string
          description: Name of the error.
          example: AuthenticationError
        message:
          type: string
          description: Error message.
          example: Login or password is incorrect
      required:
        - collector
        - version
        - name
        - message
security:
- BearerAuth: []
